[theme]
base                  = "dark"
backgroundColor       = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor             = "#fafafa"
primaryColor          = "#e4e4e7"
font                  = "sans serif"
